apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rental-disk
  namespace: wavve
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi